apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: docker.io/malikvti/auth-service:latest
          ports:
            - containerPort: 7070
          env:
            - name: SQLSERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: sqlserver-config
                  key: SQLSERVER_HOST
            - name: SQLSERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: sqlserver-config
                  key: SQLSERVER_PORT
            - name: SQLSERVER_DB
              valueFrom:
                configMapKeyRef:
                  name: sqlserver-config
                  key: SQLSERVER_DB
            - name: SQLSERVER_USER
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secret
                  key: username
            - name: SQLSERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secret
                  key: password
