apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: auth-service
          image: docker.io/malikvti/auth-service:1.6
          ports:
            - containerPort: 9090
          env:
            - name: PORT
              value: "9090"
            - name: DD_AGENT_HOST
              value: "datadog-agent.default.svc.cluster.local"
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: DD_TRACE_AGENT_URL
              value: "http://datadog-agent.default.svc.cluster.local:8126"
            - name: DD_SERVICE_NAME
              value: "auth-service"
            - name: DD_ENV
              value: "production"
            - name: DD_VERSION
              value: "1.2"
            - name: PROFILING_ENABLED
              value: "true"
            - name: DD_APPPSEC_ENABLED
              value: "true"
            - name: DD_LOGS_ENABLED
              value: "true"
            - name: DD_SERVICE_MAPPING
              value: "sqlserver.db:auth-db"
            - name: SQLSERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: sqlserver-config
                  key: SQLSERVER_HOST
            - name: SQLSERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: sqlserver-config
                  key: SQLSERVER_PORT
            - name: SQLSERVER_DB
              valueFrom:
                configMapKeyRef:
                  name: sqlserver-config
                  key: SQLSERVER_DB
            - name: SQLSERVER_USER
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secret
                  key: username
            - name: SQLSERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secret
                  key: password
