apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 9090
  type: NodePort
